<template>
    <section class="container mx-auto flex flex-col p-8">
        <h1 class="text-4xl mb-8 font-bold">Privacy Policy</h1>
        <h2 class="text-2xl mb-4 font-semibold">Our Approach to User Data</h2>
        <p class="text-lg py-1">We firmly believe that user data should be treated as a responsibility rather than an asset. Our
            commitment is to
            minimize the collection of Personally Identifying Information (PII) to the greatest extent possible. It's
            important
            to clarify that we do not profit from the sale of your data; our earnings come from affiliate commissions,
            rewarding
            us for facilitating sales generated by our recommendations.</p>
        <p class="text-lg py-1">At no point do we seek to identify you or delve into your shopping habits or online preferences.
            Our primary goal is
            to keep data collection to a minimum.</p>
        <h2 class="text-2xl my-4 font-semibold">Purposes of Data Collection</h2>
        <p class="text-lg py-1">We gather data to address specific questions related to our service:</p>
        <ol class="my-4">
            <li class="text-lg">Which product categories are in high demand?</li>
            <li class="text-lg">How effective are our recommendations in those categories?</li>
            <li class="text-lg">Do users follow through with the product recommendations we provide?</li>
            <li class="text-lg">What features of our service do users find valuable?</li>
            <li class="text-lg">Which features of our service are considered less valuable?</li>
            <li class="text-lg">What information influences purchasing decisions?</li>
            <li class="text-lg">How many users are using our platform?</li>
        </ol>
        <p class="text-lg py-1">It's crucial to emphasize that none of these inquiries necessitate identifying individual users.
            We rely on fully
            anonymized aggregate data to empower consumers with information about their buying choices. As of today, Nicked
            does
            not maintain user accounts or store any user-specific data in our databases.</p>
        <h2 class="text-2xl my-4 font-semibold">Data Collection Instances</h2>
        <p class="text-lg py-1">We only engage in data collection when users conduct shopping searches on a select few supported
            retail and
            e-commerce websites, which, at present, is restricted to Amazon.</p>
        <p class="text-lg py-1">Regarding our Chrome extension, it's important to note that while the Chrome Web Store may
            request permission to
            "read and change site data on all the websites you visit," our actual data collection only occurs in the
            aforementioned shopping scenario. We do not access your emails or any other browsing data in any way.</p>
        <p class="text-lg py-1">We welcome the Chrome team to revise permissions to allow us to request a more limited set of
            data.</p>
        <h2 class="text-4xl my-4 font-semibold">Types of Data Collected</h2>
        <h3 class="text-2xl mb-2 font-semibold">1. Anonymized E-commerce Product Pages</h3>
        <p class="text-lg py-1">Similar to search queries, we use this data to gauge product popularity. If you view a product
            page on Amazon and
            that product is in our database, we receive data such as:</p>
        <p class="text-lg py-1">{ 'sku': 'B0000ABCDE', 'store': 'amazon' }</p>
        <h3 class="text-2xl my-2 font-semibold">2. Anonymized Purchase Information</h3>
        <p class="text-lg py-1">If you make a purchase based on our recommendations, we receive only this data:</p>
        <p class="text-lg py-1">{ 'sku': 'B0000ABCDE', 'store': 'amazon', 'purchased': 'yes' }</p>
        <h3 class="text-2xl my-2 font-semibold">3. HTTP Server Logs</h3>
        <p class="text-lg py-1">Similar to most websites, our servers log request and response information, including IP
            addresses and user-agents.
            While we generally do not track IP addresses or user-agents, we may occasionally review similar requests for
            debugging purposes. Our goal is not to link these requests to specific users. An example log entry:</p>
        <h3 class="text-2xl my-2 font-semibold">5. Analytics</h3>
        <p class="text-lg py-1">We currently employ event analytics via Google Analytics and Amplitude for generic user-flow
            analysis, not at the
            individual user level. We plan to replace these services with our own minimal and relevant data collection once
            feasible.</p>
        <p class="text-md py-1">(In the interest of transparency, please be aware of our use of these services. We apologize for
            any inconvenience.)
        </p>
        <p class="text-lg py-1">An example of user-flow data obtained through Amplitude:</p>
        <p class="text-lg py-1">191 users clicked "Filter products."</p>
        <p class="text-lg py-1">92 of these users successfully filtered the recommended list.</p>
        <p class="text-lg py-1">12 users clicked on one of the displayed products.</p>
        <h2 class="text-4xl my-4 font-semibold">Opt-In Product-Specific Data</h2>
        <p class="text-lg py-1">You have the option to provide your email address to receive deal notifications for your
            preferred product
            categories. If you choose to do so, your email will be managed by a third party (MailChimp) and will not be
            associated with Nicked's extension or website usage. You can unsubscribe at any time, and if you have no
            subscribed
            categories, your email address will be deleted from our records.</p>
        <p class="text-lg py-1">Defining "Completely Anonymized"</p>
        <p class="text-lg py-1">When we refer to "completely anonymized," we mean that no personal data is attached in any form.
            There are no
            tracking cookies, IP addresses, user agents, or similar information. We only store the data outlined here along
            with
            a timestamp.</p>
        <p class="text-lg py-1"><a href="/">Nicked</a> contains links to various websites, including product reviews and online
            stores. Some of these
            links may be affiliate links, allowing us to earn commissions on products sold. These links do not contain any
            Personally Identifiable Information (PII), and we do not receive reports about individual users' purchases.
            However,
            affiliate sites may provide us with aggregate data on customer purchases. Keep in mind that websites outside of
            Nicked have their own data collection practices and privacy policies that are beyond our control.</p>
        <p class="text-lg py-1">Our future offerings may include personalization, but these features will be opt-in and subject
            to additional
            policies that clarify any expanded data collection.</p>
    </section>
</template>
